# Generated by Django 4.2 on 2025-10-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("chat", "0002_alter_contactmodels_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmodels",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="accounts.profile",
            ),
        ),
    ]
