# Generated by Django 4.2 on 2025-10-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_contactmodels_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagemodels",
            name="chat",
        ),
    ]
