# Generated by Django 4.2 on 2025-11-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_remove_messagemodels_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemodels",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatmodels",
            ),
        ),
    ]
