# Generated by Django 4.2 on 2025-11-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_messagemodels_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmodels",
            name="last_message",
        ),
        migrations.RemoveField(
            model_name="messagemodels",
            name="chat",
        ),
        migrations.AddField(
            model_name="messagemodels",
            name="last_message",
            field=models.BooleanField(default=False),
        ),
    ]
