# Generated by Django 4.2 on 2025-11-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_remove_chatmodels_last_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagemodels",
            name="last_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
