# Generated by Django 4.2 on 2025-11-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_messagemodels_last_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagemodels",
            name="last_message",
        ),
    ]
