# Generated by Django 4.2 on 2026-07-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_remove_messagemodels_last_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemodels",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="message_files/"),
        ),
        migrations.AddField(
            model_name="messagemodels",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="messagemodels",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("file", "File"),
                    ("location", "Location"),
                    ("contact", "Contact"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="messagemodels",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
