# Generated by Django 4.2 on 2026-08-02 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0011_alter_messagemodels_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmodels",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="contactmodels",
            unique_together={("user", "contact")},
        ),
    ]
