# Generated by Django 4.2 on 2026-08-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_contactmodels_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemodels",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagemodels",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
