# Generated by Django 4.2 on 2026-08-07 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_text",
                    models.CharField(
                        blank=True,
                        default="سلام! من از چتیفای استفاده می\u200cکنم.",
                        max_length=140,
                    ),
                ),
                ("two_step_enabled", models.BooleanField(default=False)),
                (
                    "last_seen_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("contacts", "My Contacts"),
                            ("nobody", "Nobody"),
                        ],
                        default="everyone",
                        max_length=10,
                    ),
                ),
                (
                    "photo_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("contacts", "My Contacts"),
                            ("nobody", "Nobody"),
                        ],
                        default="everyone",
                        max_length=10,
                    ),
                ),
                (
                    "about_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("contacts", "My Contacts"),
                            ("nobody", "Nobody"),
                        ],
                        default="everyone",
                        max_length=10,
                    ),
                ),
                ("read_receipts", models.BooleanField(default=True)),
                ("online_status_visible", models.BooleanField(default=True)),
                ("notif_messages", models.BooleanField(default=True)),
                ("notif_groups", models.BooleanField(default=True)),
                ("notif_calls", models.BooleanField(default=True)),
                ("notif_preview", models.BooleanField(default=True)),
                ("notif_vibrate", models.BooleanField(default=True)),
                ("sound_enabled", models.BooleanField(default=True)),
                ("dark_theme", models.BooleanField(default=True)),
                ("enter_to_send", models.BooleanField(default=True)),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("auto_download_wifi", models.BooleanField(default=True)),
                ("auto_download_mobile", models.BooleanField(default=False)),
                (
                    "language",
                    models.CharField(
                        choices=[("fa", "فارسی"), ("en", "English")],
                        default="fa",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
    ]
