# Generated by Django 4.2 on 2026-08-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[("fa", "فارسی"), ("en", "انگلیسی"), ("de", "آلمانی")],
                default="fa",
                max_length=5,
            ),
        ),
    ]
