# Generated by Django 4.2 on 2026-08-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_alter_usersettings_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="usersettings",
            old_name="updated_at",
            new_name="updated_date",
        ),
    ]
