# Generated by Django 4.2 on 2026-08-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_rename_created_at_usersettings_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="chat_wallpaper",
            field=models.CharField(
                choices=[
                    ("default", "پیش\u200cفرض"),
                    ("slate", "سرمه\u200cای ساده"),
                    ("cyan_gradient", "گرادیان فیروزه\u200cای"),
                    ("violet_gradient", "گرادیان بنفش"),
                    ("emerald_gradient", "گرادیان سبز"),
                    ("dots", "نقطه\u200cچین"),
                ],
                default="default",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="last_backup_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
