# Generated by Django 4.2 on 2026-08-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_usersettings_chat_wallpaper_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="dark_theme",
        ),
    ]
