# Generated by Django 4.2 on 2026-08-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_remove_usersettings_dark_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="chat_wallpaper",
            field=models.CharField(
                choices=[
                    ("default", "پیش\u200cفرض"),
                    ("midnight", "نیمه\u200cشب"),
                    ("aurora", "شفق قطبی"),
                    ("sunset", "غروب"),
                    ("ocean", "اقیانوس"),
                    ("forest", "جنگل"),
                    ("grid", "شبکه\u200cای"),
                    ("dots", "نقطه\u200cچین"),
                    ("candy", "بنفش\u200cآبی"),
                    ("amber", "کهربایی"),
                    ("starry", "پرستاره"),
                    ("diagonal", "خط\u200cهای مورب"),
                    ("monochrome", "سرمه\u200cای تک\u200cرنگ"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
