# Generated by Django 4.2 on 2026-08-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chchannels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmessage",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="channelmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "متن"),
                    ("image", "عکس"),
                    ("file", "فایل"),
                    ("voice", "پیام صوتی"),
                    ("video_note", "پیام ویدیویی"),
                    ("location", "لوکیشن"),
                    ("contact", "مخاطب"),
                    ("poll", "نظرسنجی"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
