# Generated by Django 4.2 on 2026-07-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="group_avatars/"),
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
