# Generated by Django 4.2 on 2026-07-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_group_avatar_alter_group_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessages",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="group_message_files/"
            ),
        ),
        migrations.AddField(
            model_name="groupmessages",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="groupmessages",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="group_messages/"),
        ),
        migrations.AddField(
            model_name="groupmessages",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("file", "File"),
                    ("location", "Location"),
                    ("contact", "Contact"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="groupmessages",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groupmessages",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
