# Generated by Django 4.2 on 2026-08-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_groupmessages_file_groupmessages_file_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessages",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("file", "File"),
                    ("location", "Location"),
                    ("contact", "Contact"),
                    ("voice", "Voice"),
                    ("video_note", "Video note"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
